---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # 여러분의 frontend image 주소를 입력해주세요.1
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_92892be624af
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_FUNDINGBOOST
              value: https://k14f4ad097352a.user-app.krampoline.com/api/v1
          readinessProbe:
            httpGet:
              path: /
              port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
